version: "3.8"

services:
  api:
    image: albert/api:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    environment:
      - CONFIG_FILE=${CONFIG_FILE:-"/home/albert/conf/config.yml"}
    ports:
      - 8000:8000
    volumes:
     - ./conf:/home/albert/conf # a config.yml file should be in this folder

  qdrant:
    image: qdrant/qdrant:v1.9.7-unprivileged
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_PASSWORD:-"changeme"}
    ports: 
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant:/qdrant/storage

  minio:
    image: minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:-"changeme"}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    command: redis-server --dir /data --requirepass ${REDIS_PASSWORD:-"changeme"} --save 60 1 --appendonly yes
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5

volumes:
  qdrant:
  minio:
  redis:
